### PR TITLE
Improve percentages figures

### LINKED ISSUE #40: Display single-character percentages on Windows
Most percentages single characters are available on Windows CP850. However, this library currently falls back to using ASCII such as `1/3`.

Ubuntu 20.10 Gnome terminal:

unix_3

Windows 10 `cmd.exe` (CP850):

windows_3

However, `1/7`, `1/9` and `1/10` are not supported on CP850.

Removing support for those three (arguably not-often-used) characters would allow switching to single characters percentages instead. This would also provide with a more consistent cross-platform experience.

What do you think?

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #40.

This improves the figures related to percentages on Windows.

As mentioned in the issue, `1/7`, `1/9` and `1/10` are not supported on CP850, so are kept as ASCII.

Ubuntu 20.10 Gnome terminal:

unix_3

Windows 10 `cmd.exe` (CP850):

windows_3

### CODE REVIEW

**Comment by sindresorhus** [comment]
Are you done with changes? If so, I'm gonna do a new release.

**Comment by ehmicky** [comment]
I have a few more changes coming up today indeed!

**Comment by sindresorhus** [comment]
Ok. Let me know when you're done then 👍

**Comment by ehmicky** [comment]
Done! 
There are several issues I opened which I could also do now, depending on whether you think they are a good idea. None of them are breaking changes.

**Pull request merged**
