### PR TITLE
Updated `is-unicode-supported`

### PR DESCRIPTION
**Pull request by XFaonAE**
Finally figures wont think i'm running a term emu from the 18 hundreds xD

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks, but this is not needed. Semver handles this for us. Read more here: https://nodesource.com/blog/semver-tilde-and-caret

**Comment by XFaonAE** [comment]
> Thanks, but this is not needed. Semver handles this for us. Read more here: https://nodesource.com/blog/semver-tilde-and-caret

I removed my `node_modules` directory and noticed the changes i made to `is-unicode-supported` didnt show up after install, currently i'm using a script to get the latest index.js from is-unicode-supported and writing it to the node_modules.

Is the package-lock.json cache causing this?

**Comment by sindresorhus** [comment]
> Is the package-lock.json cache causing this?

Probably

**Comment by sindresorhus** [comment]
Ok, here you go: https://github.com/sindresorhus/figures/releases/tag/v4.0.1

**Comment by XFaonAE** [comment]
❤️ Thanks!

**Pull request closed without merging**
